### ISSUE TITLE
Coin transfer error

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/SkyCommands#44]
Discord thread: https://discord.com/channels/267680588666896385/1156306581345022194/1156309630524346538
`MySqlConnector.MySqlException (0x80004005): Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb4_general_ci,COERCIBLE) for operation '='`
```
at Coflnet.Sky.Core.UserService.GetUserIdByEmail(String email) in /build/dev/Server/Services/UserService.cs:line 66
   at Coflnet.Sky.Commands.TransferCoinsCommand.Execute(MessageData data) in /build/SkyCommand/Commands/Premium/TransferCoinsCommand.cs:line 18
```

**Comment by Ekwav** [comment]
not reproduceable was able to send coins just fine
